# flag changelog

## Feature
- Add WithoutEnvironment functions ([#2](https://github.com/sascha-andres/flag/issues/2))
- Add Usage function ([#1](https://github.com/sascha-andres/flag/issues/1))
- Add initial implementation

## Other
- Add reamde

generated by git-cl, another project by Sascha Andres
